services:
  postgres:
    image: postgres:latest
    container_name: alume_postgres
    restart: always
    environment:
      POSTGRES_USER: alume
      POSTGRES_PASSWORD: alume123
      POSTGRES_DB: alume_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
